### PR TITLE
More translations and spelling fixes.

### PR DESCRIPTION
**Pull request by MDMCK10**

### CODE REVIEW

**Comment by Becold** [comment]
Le "problème" de certains de ces changements, c'est que tu rajoutes du contenu dans la traduction en anglais, qui ne se trouve du coup pas dans la traduction en français.

**Comment by MDMCK10** [comment]
I mean, even if those things aren't in the french translation, they are still valid.

**Comment by Becold** [comment]
I agree.
My bad, I thought you were speaking french too. :)

**Comment by MDMCK10** [comment]
Well, wasn't it obvious from the title of this PR?

**Comment by jeuxjeux20** [comment]
How much i bet you used google traduction :p

**Pull request merged**
